[versions]
nook-core = "1.0.6"
paper = "1.20.1-R0.1-SNAPSHOT"
worldguard = "7.0.9"

[libraries]
nookcore = { group = "es.angelillo15.core", name = "nookcore-core", version.ref = "nook-core" }
paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
worldguard = { group = "com.sk89q.worldguard", name = "worldguard-bukkit", version.ref = "worldguard" }