#
#   ▄▄▄·  ▐ ▄ ▄▄▄▄▄▪   ▄▄▄· ▄▄▄▄· ▄• ▄▌.▄▄ · ▄▄▄ .▄▄▄  .▄▄ ·
#  ▐█ ▀█ •█▌▐█•██  ██ ▐█ ▀█ ▐█ ▀█▪█▪██▌▐█ ▀. ▀▄.▀·▀▄ █·▐█ ▀.
#  ▄█▀▀█ ▐█▐▐▌ ▐█.▪▐█·▄█▀▀█ ▐█▀▀█▄█▌▐█▌▄▀▀▀█▄▐▀▀▪▄▐▀▀▄ ▄▀▀▀█▄
#  ▐█ ▪▐▌██▐█▌ ▐█▌·▐█▌▐█ ▪▐▌██▄▪▐█▐█▄█▌▐█▄▪▐█▐█▄▄▌▐█•█▌▐█▄▪▐█
#   ▀  ▀ ▀▀ █▪ ▀▀▀ ▀▀▀ ▀  ▀ ·▀▀▀▀  ▀▀▀  ▀▀▀▀  ▀▀▀ .▀  ▀ ▀▀▀▀
#
# This is the Config file for AntiAbusers
# when you can customize the plugin to your liking.
#
# If you have any questions, please contact me on Discord:
#   Discord: https://discord.nookure.com
#