#
#   ▄▄▄·  ▐ ▄ ▄▄▄▄▄▪   ▄▄▄· ▄▄▄▄· ▄• ▄▌.▄▄ · ▄▄▄ .▄▄▄  .▄▄ ·
#  ▐█ ▀█ •█▌▐█•██  ██ ▐█ ▀█ ▐█ ▀█▪█▪██▌▐█ ▀. ▀▄.▀·▀▄ █·▐█ ▀.
#  ▄█▀▀█ ▐█▐▐▌ ▐█.▪▐█·▄█▀▀█ ▐█▀▀█▄█▌▐█▌▄▀▀▀█▄▐▀▀▪▄▐▀▀▄ ▄▀▀▀█▄
#  ▐█ ▪▐▌██▐█▌ ▐█▌·▐█▌▐█ ▪▐▌██▄▪▐█▐█▄█▌▐█▄▪▐█▐█▄▄▌▐█•█▌▐█▄▪▐█
#   ▀  ▀ ▀▀ █▪ ▀▀▀ ▀▀▀ ▀  ▀ ·▀▀▀▀  ▀▀▀  ▀▀▀▀  ▀▀▀ .▀  ▀ ▀▀▀▀
#
# This is the Config file for AntiAbusers
# when you can customize the plugin to your liking.
#
# If you have any questions, please contact me on Discord:
#   Discord: https://discord.nookure.com
#
Config:
  # The language files to use
  # These are the available languages:
  #   - en (English)
  #   - es (Spanish)
  language: en
  # Enable or disable the debug mode (true/false)
  # When enabled, the plugin will print debug messages to the console
  # This is useful for debugging the plugin and finding errors
  debug: false
  # Delay in seconds to check the player's inventory
  playerAsyncInventoryCheckDelay: 5
  # Allow players to attack other players when they are in different regions
  allowDifferentRegionsAttack: false
  # How many seconds to wait before the player who attacked an abuser
  # would be protected from the abuser again
  pvpTimer: 10
  # Warn the player when he/she enters a region where he/she
  # is considered an abuser
  warnOnEnter: true
  # Warn and cancel when the player tries to attack an abuser,
  # This will prevent the player from doing the first hit
  # and will warn him/her that he/she is attacking an abuser,
  # and will cancel the attack if the player continues to attack
  # the abuser after the warning message could be attacked
  # by the abuser.
  warnAndCancelOnAttack: true
  # Cancel attacks to an abuser
  # This will prevent the player from attacking an abuser
  # and will warn him/her that he/she is attacking an abuser,
  # and will cancel the attack if the player continues to attack
  cancelAbuserAttack: false
  # If you enable this option, the plugin will ignore the regions
  # that are in the ignoreRegionsList, this is useful if you
  # have a parent region that contains other regions, and you
  # want to ignore the child regions.
  ignoreRegions: false
  # List of regions to ignore
  ignoreRegionsList:
    - region1
    - region2