name: AntiAbusers
version: "${version}"
api-version: "1.19"
author: Angelillo15
loader: es.angelillo15.antiabusers.DependencyLoader
main: es.angelillo15.antiabusers.AntiAbusersLoader
provides: [WorldGuard]
dependencies:
  server:
    WorldGuard:
      load: BEFORE
      required: true
      join-classpath: true
load-before:
  - name: WorldGuard
    bootstrap: false